### ISSUE TITLE
pyrostarter don't work

### ISSUE THREAD

**Issue by nek-v** [ahmetveburak/pyrostarter#13]
When I try to run I get this error
```
(.venv) D:\home\dev\python\pyrogram-template\test>pyrostarter init
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\home\dev\python\pyrogram-template\.venv\Scripts\pyrostarter.exe\__main__.py", line 7, in <module>
  File "d:\home\dev\python\pyrogram-template\.venv\lib\site-packages\pyrostarter\pyrostarter.py", line 10, in main
    application.add(ConfigCommand())
  File "d:\home\dev\python\pyrogram-template\.venv\lib\site-packages\pyrostarter\commands\config.py", line 29, in __init__
    self.create_config()
  File "d:\home\dev\python\pyrogram-template\.venv\lib\site-packages\pyrostarter\commands\config.py", line 35, in create_config
    self.line("<comment>Config file cleared.</>")
  File "d:\home\dev\python\pyrogram-template\.venv\lib\site-packages\cleo\commands\command.py", line 233, in line
    self._io.write_line(styled, verbosity)
AttributeError: 'NoneType' object has no attribute 'write_line'```

**Comment by ahmetveburak** [comment]
Thank you. I was not updating the project for a long time. I will fix it asap.

**Comment by ahmetveburak** [comment]
@nek-v you can reinstall or update the pyrostarter. It should be working now.
